# Generated by Django 2.2.17 on 2021-01-28 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(0, "Meh..."), (1, "Whaaaat?"), (2, "Noooo!")],
                        default=0,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "articles_article",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="ArticleComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        related_query_name="comment",
                        to="articles.Article",
                    ),
                ),
            ],
            options={
                "db_table": "articles_article_comment",
                "ordering": ["created"],
            },
        ),
    ]
